### ISSUE TITLE
Feature request: Output for onSelection

### ISSUE THREAD

**Issue by SuperVillainPresident** [lmelvin/ng6-combobox#1]
This is really simple and I like it. Could you add an Output for when a selection is made/custom text is entered?

**Comment by lmelvin** [comment]
So on the selection output, would you prefer it pass the entire selected object in the array or just the value?

**Comment by SuperVillainPresident** [comment]
For what I would use it for, just the text would be sufficient. On the chance that the source is just a string array, all I'd get back would be a string anyways. Then I wouldn't know whether it was in the source or not, so I'd have to do a look up in the source for it to see if it is there. Thanks!

**Comment by lmelvin** [comment]
@SuperVillainPresident I implemented this and updated the readme and committed to the master branch. I also updated the npm package to 1.0.4.

Keep in mind that these outputs only trigger for mouse click for `selectItem` and text input changes for `textChange`. If you cycle through using the up/down keyboard arrows neither will be triggered. However, you may be able to use `ngModelChange` for that.

**Comment by SuperVillainPresident** [comment]
thank you so much!
